#import <Foundation/Foundation.h>
@interface VoiceViewConditionControllerCircleIndicatorViewd: NSObject
+ (BOOL)cInitwithcoder:(NSInteger)VoiceViewConditionController;
+ (BOOL)nInitwithframe:(NSInteger)VoiceViewConditionController;
+ (BOOL)psetup:(NSInteger)VoiceViewConditionController;
+ (BOOL)ilayoutSubviews:(NSInteger)VoiceViewConditionController;
+ (BOOL)pDrawrect:(NSInteger)VoiceViewConditionController;
+ (BOOL)jinitializeUI:(NSInteger)VoiceViewConditionController;
+ (BOOL)ZupdateUI:(NSInteger)VoiceViewConditionController;
+ (BOOL)FdisableMinusButton:(NSInteger)VoiceViewConditionController;
+ (BOOL)RenableMinusButton:(NSInteger)VoiceViewConditionController;
+ (BOOL)msetupDefaultDataThatIsNotRelatedToFrame:(NSInteger)VoiceViewConditionController;
+ (BOOL)HsetDataThatIsRelatedToFrameToCustomRatio:(NSInteger)VoiceViewConditionController;
+ (BOOL)IconfigureDataToFitSize:(NSInteger)VoiceViewConditionController;
+ (BOOL)fcalculateDataAccordingDynamicValue:(NSInteger)VoiceViewConditionController;
+ (BOOL)raddLayer1:(NSInteger)VoiceViewConditionController;
+ (BOOL)faddLayer2:(NSInteger)VoiceViewConditionController;
+ (BOOL)qaddLayer3:(NSInteger)VoiceViewConditionController;
+ (BOOL)UShinewithtimeintervalxPausedurationGFinalvaluekFinishblock:(NSInteger)VoiceViewConditionController;
+ (BOOL)gChangeindicatorfromvaluepTovalueWIsshowaccessorywhenfinishediDuration:(NSInteger)VoiceViewConditionController;
+ (BOOL)COperationfromvalueqTovalueRTimeintervallIsshowaccessorywhenfinished:(NSInteger)VoiceViewConditionController;
+ (BOOL)HCalculatefourkeypointforrectanglewithcirclecenterVInnercircleradiusKRectanglewidhtpRectangleheightnAngle:(NSInteger)VoiceViewConditionController;
+ (BOOL)IShowaccessoryonlinewitlinenumber:(NSInteger)VoiceViewConditionController;
+ (BOOL)ALinenumberwithindicatorvalue:(NSInteger)VoiceViewConditionController;
+ (BOOL)ymaskLayerForLayer1:(NSInteger)VoiceViewConditionController;
+ (BOOL)tMasklayerforlayer2Withlinenumber:(NSInteger)VoiceViewConditionController;
+ (BOOL)EmaskLayerForLayer3:(NSInteger)VoiceViewConditionController;
+ (BOOL)bminusButtonClick:(NSInteger)VoiceViewConditionController;
+ (BOOL)taddButtonClick:(NSInteger)VoiceViewConditionController;
+ (BOOL)WclearIndicatorValue:(NSInteger)VoiceViewConditionController;
+ (BOOL)qSetindicatorvaluekAnimated:(NSInteger)VoiceViewConditionController;
+ (BOOL)Tqueue:(NSInteger)VoiceViewConditionController;
+ (BOOL)NSetindicatorvalue:(NSInteger)VoiceViewConditionController;
+ (BOOL)RSetcentervalue:(NSInteger)VoiceViewConditionController;
+ (BOOL)QSetenable:(NSInteger)VoiceViewConditionController;
+ (BOOL)xSethotstatusonoff:(NSInteger)VoiceViewConditionController;
+ (BOOL)oSetinnerannulusvaluetoshowarray:(NSInteger)VoiceViewConditionController;

@end
