#import <UIKit/UIKit.h>
#import "RectangleIndicatorView.h"

@interface RectangleIndicatorView (Voiceviewconditioncontroller)
+ (BOOL)initWithCoderVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)initWithFrameVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)setupVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)layoutSubviewsVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)drawRectVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)initializeUIVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)updateUIVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)setupDefaultDataThatIsNotRelatedToFrameVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)setDataThatIsRelatedToFrameToCustomRatioVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)configureDataToFitSizeVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)addLayer1Voiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)addLayer2Voiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)shineWithTimeIntervalPausedurationFinalvalueFinishblockVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)operationFromValueTovalueTimeintervalIsshowaccessorywhenfinishedVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)changeIndicatorFromValueTovalueIsshowaccessorywhenfinishedDurationVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)calculateDataAccordingDynamicValueVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)calculateFourKeyPointForRectangleWithStartPointMovexLinewidthLineheigthIsprotrudingupIsprotrudingdownVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)showAccessoryOnLineWitLineNumberVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)lineNumberWithIndicatorValueVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)maskLayerForLayer1Voiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)maskLayerForLayer2WithLineNumberVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)minusButtonClickVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)addButtonClickVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)clearIndicatorValueVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)setIndicatorValueAnimatedVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)queueVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)setIndicatorValueVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)setCenterValueVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)setEnableVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)setHotStatusOnOffVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)setMinValueVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)setMaxValueVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;
+ (BOOL)setValueToShowArrayVoiceviewconditioncontroller:(NSInteger)VoiceViewConditionController;

@end
